// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CLAW_H
#define CLAW_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */

// Some parameters for claw positioning
float clawOpenTarget = 1.0;
float clawClosedTarget = 0.0;

class Claw: public Subsystem {
private:
	int mode;
	enum modeType {OFF, POSITION, RATE};
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* sc;
	Encoder* encoder;
	PIDController* controller;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Claw();
	//void UsePIDOutput();
	void Stop();
	void InitDefaultCommand();
	void SetPositionMode();
	void SetRateMode();
	void UpdateController();
};

#endif
