/*
 * drivePIDoutput.h
 *
 *  Created on: Jan 17, 2015
 *      Author: concord robotics
 */

// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEPIDOUTPUT_H
#define DRIVEPIDOUTPUT_H
#include <PIDOutput.h>
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class drivePIDOutput: public PIDOutput {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	drivePIDOutput(float output);
	float PIDOutput;
    void PIDWrite(float output);

};
#endif



