// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Lift.h"
#include "../RobotMap.h"
#include "Robot.h"
#include "LiveWindow/LiveWindow.h"
#include "Commands/LinearSysRate.h"


Lift::Lift() : LinearSystem(), Subsystem("Lift") {
	sc = RobotMap::liftSC;
	encoder = RobotMap::liftEncoder;
	positionController = RobotMap::liftPositionController;
	rateController = RobotMap::liftRateController;
	upperSwitch = RobotMap::liftUpperSwitch;
	lowerSwitch = RobotMap::liftLowerSwitch;
	name = new char[5];
	strcpy(name,"Lift");
	SmartDashboard::PutNumber("LiftUpper",upperSwitch->Get());
	SmartDashboard::PutNumber("LiftLower",lowerSwitch->Get());
	mode = OFF;
	Stop();
	rateController->LogData(true,"LiftRate");
	positionController->LogData(true,"LiftPos");
}



void Lift::SetFeedForward ( ) {
	// Set a constant to help support the weight of the lift
	ff = 0.2;
}

void Lift::InitDefaultCommand() {
	// Set the default command for a subsystem here.

	//SetDefaultCommand(new LinearSysRate(Robot::lift,Robot::lift,0.0));

}

void Lift::EnforceLimits() {
	// Add something for the limit switch
	// Don't reset distance to zero since the lift can unwind past zero
//	bool atBottom = false;
//	bool atTop = false;
	SmartDashboard::PutNumber("LiftUpper",upperSwitch->Get());
	SmartDashboard::PutNumber("LiftLower",lowerSwitch->Get());
//	if (lowerSwitch->Get() == CLOSED) {
//		atBottom = true;
//		encoder->Reset();
//	} else if (upperSwitch->Get() == CLOSED) {
//		atTop = true;
//	}
//	// ToDo Create some soft limits
	double distance = encoder->GetDistance();
	double penalty = 1.0;
	if (mode == RATE) {
		if (setPoint > 0.0) {
			penalty = 20.0*(limits[1] - distance)/range;
			penalty = std::max(1.0,penalty);
			setPoint = setPoint*penalty;
		} else if (setPoint < 0.0) {
			penalty = 20.0*(distance - limits[0])/range;
			penalty = std::max(1.0,penalty);
			setPoint = setPoint*penalty;
		}
		rateController -> SetSetpoint(setPoint);
		//if (atBottom and )
	}
	// Don't do anything for position - we shouldn't be commanding a negative position.
}
