// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LINEAR_SYSTEM_H
#define LINEAR_SYSTEM_H

#include "Support/cPIDController.h"
#include "Support/ControllerLimits.h"
#include "Support/PIDParams.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */

class LinearSystem {
protected:
	int mode;
	double setPoint = 0.0;
	double output = 0.0;
	SpeedController* sc;
	Encoder* encoder;
	PIDParams* positionGains;
	PIDParams* rateGains;
	ControllerLimits* lim;
	virtual void EnforceLimits() {};
	virtual void SetFeedForward() {};
 public:
	cPIDController* controller;
	char* name = NULL;
	LinearSystem();
	void Stop();
	void SetSetpoint(double setSetpoint);
	virtual void InitDefaultCommand();
	void SetMode(int modeIn);
	void UpdateController();
	virtual ~LinearSystem() {};
	double PositionError(double target);
};

#endif
