// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ADVANCEDJOYSTICK_H
#define ADVANCEDJOYSTICK_H

#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AdvancedJoystick: public Joystick {
private:
	float deadband[3];
	float eGain[3];
	float ApplyDeadBand(float input, int channel);
	float ApplyEGain(float input, int channel);
public:
	AdvancedJoystick(uint32_t port, float deadbandIn[3], float eGainIn[3]);
	float aGetX (void);
	float aGetY (void);
	float aGetTwist (void);

};

#endif
