// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ClawPosition.h"
#include "Subsystems/Claw.h"

ClawPosition::ClawPosition(float position) {
	// Use requires() here to declare subsystem dependencies
	Requires(Robot::claw);
	Robot::claw->SetPositionMode();
	Robot::claw->controller->SetSetpoint(position);
}

// Called just before this Command runs the first time
void ClawPosition::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void ClawPosition::Execute() {
	Robot::claw->UpdateController();
}

// Make this return true when this Command no longer needs to run execute()
bool ClawPosition::IsFinished() {
	return (Robot::claw->controller->OnTarget());
}

// Called once after isFinished returns true
void ClawPosition::End() {
	Robot::claw->Stop();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClawPosition::Interrupted() {
	Robot::claw->Stop();
}
