// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LiftHigh.h"
#include "Support/SingleMotor.h"

LiftHigh::LiftHigh() {
	// Use requires() here to declare subsystem dependencies
	Requires(Robot::lift);
    // Set the controller to go to a position by reseting it and passing it false
	// for whether or not it is rate controlled.
    Robot::lift->liftMotor->Reset(false);
    // ToDo: add checks to see if lift is above or below the top, and reset the encoder
    // postion and prevent the lift from moving further up or down

}

// Called just before this Command runs the first time
void LiftHigh::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void LiftHigh::Execute() {
    // Set the target at 30 inches.  This is referenced from the original starting
    // position, so ensure lift is at bottom
	Robot::lift->SetPosition(30.0);
    Robot::lift->liftMotor->OutputToDashboard("Lift");
}

// Make this return true when this Command no longer needs to run execute()
bool LiftHigh::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void LiftHigh::End() {
	Robot::lift->SetPower(0.0);
	Robot::lift->liftSC->Set(0.0);

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftHigh::Interrupted() {
	Robot::lift->SetPower(0.0);
	Robot::lift->liftSC->Set(0.0);
}
