// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LINEARHOLDPOSITION_H
#define LINEARHOLDPOSITION_H

#include "../Robot.h"
#include "Commands/LinearSysPosition.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LinearHoldPosition : public Command {
protected:
	LinearSystem* sys;
public:
	LinearHoldPosition(Subsystem* sysIn,  LinearSystem* linSys);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
