// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SetDriveMode.h"

SetDriveMode::SetDriveMode(int driveModeIn) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	driveMode = driveModeIn;
    modeSet = false;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void SetDriveMode::Initialize() {
	modeSet = false;
}

// Called repeatedly when this Command is scheduled to run
void SetDriveMode::Execute() {
	Robot::driveMotors->SetDriveMode(driveMode);
	for (int i = 0; i < 4; i++) {
		Robot::driveMotors->controllers[i]->Reset(Robot::driveMotors->encoders[i]->GetDistance());
	}
	modeSet = true;
}

// Make this return true when this Command no longer needs to run execute()
bool SetDriveMode::IsFinished() {
	if (modeSet) {
		modeSet = false;
		return true;
	} else return false;
}

// Called once after isFinished returns true
void SetDriveMode::End() {


}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetDriveMode::Interrupted() {

}
