// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveMotorsSpeedController1 = NULL;
SpeedController* RobotMap::driveMotorsSpeedController3 = NULL;
SpeedController* RobotMap::driveMotorsSpeedController2 = NULL;
SpeedController* RobotMap::driveMotorsSpeedController4 = NULL;
RobotDrive* RobotMap::driveMotorsRobotDrive = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveMotorsSpeedController1 = new Talon(0);
	lw->AddActuator("DriveMotors", "SpeedController1", (Talon*) driveMotorsSpeedController1);
	
	driveMotorsSpeedController3 = new Talon(2);
	lw->AddActuator("DriveMotors", "SpeedController3", (Talon*) driveMotorsSpeedController3);
	
	driveMotorsSpeedController2 = new Talon(3);
	lw->AddActuator("DriveMotors", "SpeedController2", (Talon*) driveMotorsSpeedController2);
	
	driveMotorsSpeedController4 = new Talon(4);
	lw->AddActuator("DriveMotors", "SpeedController4", (Talon*) driveMotorsSpeedController4);
	
	driveMotorsRobotDrive = new RobotDrive(driveMotorsSpeedController1, driveMotorsSpeedController2,
              driveMotorsSpeedController3, driveMotorsSpeedController4);
	
	driveMotorsRobotDrive->SetSafetyEnabled(true);
        driveMotorsRobotDrive->SetExpiration(0.1);
        driveMotorsRobotDrive->SetSensitivity(0.5);
        driveMotorsRobotDrive->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
